### ISSUE TITLE
providers

### ISSUE THREAD

**Issue by afreisinger** [thobiast/terraform-openstack-loadbalancer#3]
Hi thobiast, I am confused

terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of terraform-provider-openstack/openstack from the dependency lock file
- Reusing previous version of hashicorp/local from the dependency lock file
- Finding latest version of hashicorp/openstack...
- Using previously-installed terraform-provider-openstack/openstack v1.32.0
- Using previously-installed hashicorp/local v2.1.0

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/openstack: provider registry registry.terraform.io does not have a
provider named registry.terraform.io/hashicorp/openstack

If you have just upgraded directly from Terraform v0.12 to Terraform v0.14
then please upgrade to Terraform v0.13 first and follow the upgrade guide for
that release, which might help you address this problem.

Did you intend to use terraform-provider-openstack/openstack? If so, you must
specify that source address in each module which requires that provider. To
see which modules are currently depending on hashicorp/openstack, run the
following command:
    terraform providers

I use terraform-provider-openstack/openstack

My lb.tf 

module "loadbalancer" { 
  source            = "git::https://github.com/thobiast/terraform-openstack-loadbalancer.git" 
  name              = "test-http" 
  lb_description    = "Test load balancer using terraform module" 
  lb_vip_subnet_id  = var.public_subnet_id 
  member_address    = openstack_compute_instance_v2.simple-web[*].access_ip_v4 
  member_subnet_id  = var.private_subnet_id 
}

**Comment by afreisinger** [comment]
Failed to instantiate provider "registry.terraform.io/hashicorp/openstack" to
obtain schema: unknown provider "registry.terraform.io/hashicorp/openstack"

terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/terraform-provider-openstack/openstack] ~> 1.32.0
├── provider[registry.terraform.io/hashicorp/local]
└── module.openstack-lb
    └── provider[registry.terraform.io/hashicorp/openstack]

**Comment by thobiast** [comment]
Hi afreisinger, 

The provider definition changed on terraform 13. I have just uploaded a new version that is compatible with Terraform v0.13 and v0.14

Thank you.
