### ISSUE TITLE
Loadbalancer setup with 80 and 443?

### ISSUE THREAD

**Issue by till** [thobiast/terraform-openstack-loadbalancer#6]
Just glanced over the code, and I can see that I can do http, https or TCP and then it sets the ports. Wouldn't you need port 80 *and* 443 in most cases?

**Comment by thobiast** [comment]
Hi,

Yes, in most cases. However, you can customize to use other ports like 8080, 8443, etc.

**Comment by till** [comment]
@thobiast How do you currently do that with your module?

**Comment by till** [comment]
I mean, not the custom port, but two ports on one loadbalancer. Seems like an additional listener is missing. I can send a PR later if you'd take the contribution.

**Comment by thobiast** [comment]
The current version does not support more than one listener per load balancer.

Some time ago, I worked on a new version to add multiple listeners. It is still a WIP, but works. Please, take a look at 'dev' branch.

The syntax is different.

```hcl
module "openstack-lb" {
  name                  = "multiple_listeners"
  lb_description        = "Test load balancer with multiple listeners"
  lb_security_group_ids = [openstack_networking_secgroup_v2.my_lb.id]
  lb_vip_subnet_id      = xxxxx-yyyyyy
  listeners = {
    https_lb1 = {
      listener_protocol               = "TERMINATED_HTTPS"
      listener_protocol_port          = 443
      lb_pool_protocol                = "HTTP"
      member_address                  = openstack_compute_instance_v2.http[*].access_ip_v4
      member_subnet_id                = aaaaa-bbbbb
      tls_container_ref               = openstack_keymanager_container_v1.tls_1.container_ref
    },
    http_lb1 = {
      listener_protocol               = "HTTP"
      lb_pool_protocol                = "HTTP"
      member_address                  = openstack_compute_instance_v2.http[*].access_ip_v4
      member_subnet_id                = aaaaa-ccccc
    },
```

Feel free to send a PR. Contributions are welcome

**Comment by till** [comment]
@thobiast I have a full example, that could "serve" as a test. I'll PR that first.

Other things:

1. Want to figure out how to turn on HA-mode
2. Want to figure out what it takes to assign a FIP to the LB

**Comment by till** [comment]
On the second part, it looks like:

```tf
resource "openstack_compute_floatingip_v2" "floating_ip" {
  pool = "public"
}

resource "openstack_networking_port_v2" "port_floating" {
  network_id = "a5bbd213-e1d3-49b6-aed1-9df60ea94b9a"
}

resource "openstack_networking_floatingip_associate_v2" "fip_to_port" {
  floating_ip = openstack_compute_floatingip_v2.floating_ip.address
  port_id     = openstack_networking_port_v2.port_floating.id
}
```

And then use `openstack_networking_port_v2.port_floating.id` with your module.

Roughly around here:
https://github.com/thobiast/terraform-openstack-loadbalancer/blob/dev/main.tf#L4-L10

I'll PR that next and then I can add that as an example as well? Maybe a docs folder?

**Comment by thobiast** [comment]
Hi,

Regarding the first point. I am not sure if I got you. HA is configured at Octavia level.

I have not tested, but this should work to assign a FIP to the LB

```hcl
resource "openstack_networking_floatingip_v2" "floatip_1" {
  pool      = "fip_pool"
  port_id     = module.openstack-lb.loadbalancer_vip_port_id
}
```
or using two steps:

```hcl
resource "openstack_networking_floatingip_v2" "floatip_1" {
  pool      = "fip_pool"
}

resource "openstack_networking_floatingip_associate_v2" "fip_1" {
  floating_ip = openstack_networking_floatingip_v2.floatip_1.address
  port_id     = module.openstack-lb.loadbalancer_vip_port_id
}
```
We can add some different scenario examples in docs folder. You can also add a full working example, that way it is not required to add a test folder.

Thanks

**Comment by till** [comment]
> Hi,
> 
> 
> 
> Regarding the first point. I am not sure if I got you. HA is configured at Octavia level.
> 
> 
> 
> I have not tested, but this should work to assign a FIP to the LB
> 
> 
> 
> ```hcl
> 
> resource "openstack_networking_floatingip_v2" "floatip_1" {
> 
>   pool      = "fip_pool"
> 
>   port_id     = module.openstack-lb.loadbalancer_vip_port_id
> 
> }
> 
> ```
> 
> or using two steps:
> 
> 
> 
> ```hcl
> 
> resource "openstack_networking_floatingip_v2" "floatip_1" {
> 
>   pool      = "fip_pool"
> 
> }
> 
> 
> 
> resource "openstack_networking_floatingip_associate_v2" "fip_1" {
> 
>   floating_ip = openstack_networking_floatingip_v2.floatip_1.address
> 
>   port_id     = module.openstack-lb.loadbalancer_vip_port_id
> 
> }
> 
> ```
> 
> We can add some different scenario examples in docs folder. You can also add a full working example, that way it is not required to add a test folder.
> 
> 
> 
> Thanks
> 
> 

Makes sense, I'll do that in docs.

I am still looking re: ha, our Openstack distro has an option to enable HA. Essentially multiple haproxy instances with keepalived. So I am guessing that is Octavia, but I wanted to enable it through Terraform somehow. But I will dig into terraform and gophercloud to see if that is exposed.

So the reason why I want to add the port variable is that the lb otherwise gets another public IP. And I am trying to run it only with the floating IP to preserve IPs.

**Comment by till** [comment]
Re: fip, I see what you mean now. Thanks for merging though. :)

I am trying to figure out if the openstack loadbalancer flavours is what gets me HA. I might send a PR for flavor_id.

**Comment by till** [comment]
@thobiast so, the last push adds support for the `flavor_id`, this allows the use of Octavia flavor's, aka, HA.

**Comment by thobiast** [comment]
Hi,

Those issues are fixed in dev branch.

Thank you
